#!/usr/bin/env python
from optparse import OptionParser
import os, sys, time, shutil
from logging import info, debug, warn

from zeroinstall import SafeException
from zeroinstall.injector.iface_cache import iface_cache
from zeroinstall.injector import basedir, model, namespaces, policy, handler

version = '0.1'

parser = OptionParser(usage="usage: %prog [options] PUBLIC-DIR")
parser.add_option("-v", "--verbose", help="more verbose output", action='count')
parser.add_option("-V", "--version", help="display version information", action='store_true')

(options, args) = parser.parse_args()

if options.version:
	print "0mirror (zero-install) " + version
	print "Copyright (C) 2007 Thomas Leonard"
	print "This program comes with ABSOLUTELY NO WARRANTY,"
	print "to the extent permitted by law."
	print "You may redistribute copies of this program"
	print "under the terms of the GNU General Public License."
	print "For more information about these matters, see the file named COPYING."
	sys.exit(0)

if options.verbose:
	import logging
	logger = logging.getLogger()
	if options.verbose == 1:
		logger.setLevel(logging.INFO)
	else:
		logger.setLevel(logging.DEBUG)

if len(args) != 1:
	parser.print_help()
	sys.exit(1)
public_dir = args[0]

feed_file = os.path.join(public_dir, 'feed-list')

def escape_slashes(path):
	return path.replace('/', '#')

try:
	if not os.path.isdir(public_dir):
		raise SafeException("Public directory '%s' does not exist. "
				    "To setup a new site, create it as an empty directory now." % public_dir)
	if not os.path.isfile(feed_file):
		raise SafeException("File '%s' does not exist. It should contain a list of feed URLs, one per line" % feed_file)
	feeds = filter(None, file(feed_file).read().split('\n'))
	handler = handler.Handler()
	for feed in feeds:
		info("Processing feed '%s'", feed)
		if '#' in feed:
			raise SafeException("Invalid URL '%s'" % feed)
		scheme, rest = feed.split('://', 1)
		domain, rest = rest.split('/', 1)
		assert scheme in ('http', 'https', 'ftp')	# Just to check for mal-formed lines; add more as needed
		for x in [scheme, domain, rest]:
			if not x or x.startswith(','):
				raise SafeException("Invalid URL '%s'" % feed)
		feed_dir = os.path.join(public_dir, 'feeds', scheme, domain, escape_slashes(rest))
		if not os.path.isdir(feed_dir):
			os.makedirs(feed_dir)

		print "Updating", feed
		p = policy.Policy(feed, handler)
		p.stale_feeds = set()
		iface = p.get_interface(feed)	# May start a download
		for x in p.stale_feeds:
			print "Updating stale feed", feed
			p.begin_iface_download(x)
		try:
			handler.wait_for_downloads()
		except SafeException, ex:
			warn("Error updating '%s': %s", feed, str(ex))
			continue

		cached = basedir.load_first_cache(namespaces.config_site, 'interfaces', model.escape(feed))
		if not cached:
			print "Not cached", feed
			continue

		last_modified = int(os.stat(cached).st_mtime)
		version_name = time.strftime('%Y-%m-%d.xml', time.gmtime(last_modified))
		version_path = os.path.join(feed_dir, version_name)
		if os.path.exists(version_path):
			continue
		shutil.copyfile(cached, version_path)
		latest = os.path.join(feed_dir, 'latest')
		latest_new = latest + '.new'
		if os.path.exists(latest_new):
			os.unlink(latest_new)
		os.symlink(version_name, latest_new)
		os.rename(latest_new, latest)
		print "Updated %s to %s" % (feed, version_name)
except KeyboardInterrupt, ex:
	print >>sys.stderr, "Aborted at user's request"
	sys.exit(1)
except SafeException, ex:
	if options.verbose: raise
	print >>sys.stderr, ex
	sys.exit(1)
